### ISSUE TITLE
Option parameter for zoom level

### ISSUE THREAD

**Issue by Xennis** [MatthewBarker/leaflet-wikipedia#2]
When you zoom out, it looks like that:
![capture_a](https://cloud.githubusercontent.com/assets/2261834/9086892/a6aac83c-3b87-11e5-8637-ea0f83ff0eca.PNG)

Can you maybe add an option parameter to limit until which zoom level the icons get's displayed on the map? You can't click the items in this case anyway, since the most are hidden or overlapped by others.

**Comment by MatthewBarker** [comment]
Fixed, defaults to min: 0, max: 18
